FROM ruby:2.5.1

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev imagemagick

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -qq --no-install-recommends \
    nodejs \
    yarn \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV RAILS_ENV='development'
ENV RACK_ENV='development'
ENV APP_HOME /sankakukikaku/

RUN mkdir $APP_HOME
WORKDIR $APP_HOME

COPY ./app $APP_HOME
RUN bundle install -j3

RUN yarn install --check-files
